import { requireNonEmpty, sha256Id, type ReaderEntitlementSource, type ReaderEntitlementStatus } from "../reader-contracts/index.ts";
import { appendReaderAuditEvent } from "./audit-service.ts";
import { requireActiveVerifiedReader } from "./reader-profile-service.ts";
import { readerPlatformCollections, serverTimestamp, type ReaderPlatformDb, type ReaderPlatformTransaction } from "./service-support.ts";

export function deterministicEntitlementId(readerUid: string, tenantId: string, assetId: string, purchaseLineItemId?: string | null): string { return sha256Id(purchaseLineItemId ? "reader-entitlement" : "promotion-entitlement", requireNonEmpty(readerUid, "readerUid"), requireNonEmpty(tenantId, "tenantId"), requireNonEmpty(assetId, "assetId"), purchaseLineItemId || "promotion"); }
export function canAuthorizeEntitlement(data: Record<string, unknown>): boolean { return data.status === "active" && typeof data.readerUid === "string" && typeof data.tenantId === "string" && typeof data.assetId === "string"; }

export async function createEntitlementInTransaction(db: ReaderPlatformDb, transaction: ReaderPlatformTransaction, input: { readerUid: string; tenantId: string; assetId: string; purchaseId?: string | null; purchaseLineItemId?: string | null; source: ReaderEntitlementSource; correlationId: string; legacyEntitlementId?: string | null; legacyReaderAccessKey?: string | null }, existingSnapshot?: { exists: boolean; data(): Record<string, unknown> | undefined }): Promise<string> {
  if (input.source === "manual_grant") throw new Error("MANUAL_GRANT_NOT_IMPLEMENTED");
  const id = deterministicEntitlementId(input.readerUid, input.tenantId, input.assetId, input.purchaseLineItemId); const reference = db.collection(readerPlatformCollections.entitlements).doc(id); const existing = existingSnapshot || await transaction.get(reference);
  if (existing.exists) { const data = existing.data() || {}; if (data.readerUid !== input.readerUid || data.tenantId !== input.tenantId || data.assetId !== input.assetId) throw new Error("ENTITLEMENT_ID_COLLISION"); return id; }
  transaction.create(reference, { id, readerUid: input.readerUid, tenantId: input.tenantId, assetId: input.assetId, purchaseId: input.purchaseId || null, purchaseLineItemId: input.purchaseLineItemId || null, status: "active", source: input.source, lastValidatedAt: null, suspendedAt: null, revokedAt: null, refundedAt: null, legacyEntitlementId: input.legacyEntitlementId || null, legacyReaderAccessKey: input.legacyReaderAccessKey || null, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
  await appendReaderAuditEvent(db, { eventType: "entitlement.created", actorType: "system", actorId: null, subjectType: "entitlement", subjectId: id, correlationId: input.correlationId, idempotencyKey: `created:${id}`, metadata: { source: input.source, tenantId: input.tenantId, assetId: input.assetId } }, transaction); return id;
}

const transitions: Record<ReaderEntitlementStatus, ReaderEntitlementStatus[]> = { active: ["suspended", "revoked", "refunded"], suspended: ["active", "revoked", "refunded"], revoked: [], refunded: [] };
export async function transitionEntitlement(db: ReaderPlatformDb, entitlementId: string, nextStatus: ReaderEntitlementStatus, input: { correlationId: string; actorType?: "system" | "stripe" | "admin"; reason: string }): Promise<void> {
  const reference = db.collection(readerPlatformCollections.entitlements).doc(requireNonEmpty(entitlementId, "entitlementId"));
  await db.runTransaction(async (transaction) => { const snapshot = await transaction.get(reference); if (!snapshot.exists) throw new Error("ENTITLEMENT_NOT_FOUND"); const current = snapshot.data()?.status as ReaderEntitlementStatus; if (current === nextStatus) return; if (!transitions[current]?.includes(nextStatus)) throw new Error(`ENTITLEMENT_TRANSITION_INVALID:${current}:${nextStatus}`);
    transaction.update(reference, { status: nextStatus, updatedAt: serverTimestamp(), ...(nextStatus === "suspended" ? { suspendedAt: serverTimestamp() } : {}), ...(nextStatus === "revoked" ? { revokedAt: serverTimestamp() } : {}), ...(nextStatus === "refunded" ? { refundedAt: serverTimestamp() } : {}), ...(nextStatus === "active" ? { suspendedAt: null } : {}) });
    await appendReaderAuditEvent(db, { eventType: `entitlement.${nextStatus}`, actorType: input.actorType || "system", actorId: null, subjectType: "entitlement", subjectId: entitlementId, correlationId: input.correlationId, idempotencyKey: `${nextStatus}:${input.correlationId}`, metadata: { previousStatus: current, reason: input.reason } }, transaction);
  });
}
export async function authorizeReaderAsset(db: ReaderPlatformDb, readerUid: string, tenantId: string, assetId: string): Promise<boolean> { const snapshot = await db.collection(readerPlatformCollections.entitlements).where("readerUid", "==", readerUid).where("tenantId", "==", tenantId).where("assetId", "==", assetId).where("status", "==", "active").limit(1).get(); return !snapshot.empty; }
export async function listActiveReaderEntitlements(db: ReaderPlatformDb, readerUid: string): Promise<Record<string, unknown>[]> { await requireActiveVerifiedReader(db, readerUid); const snapshot = await db.collection(readerPlatformCollections.entitlements).where("readerUid", "==", requireNonEmpty(readerUid, "readerUid")).where("status", "==", "active").get(); return snapshot.docs.map((document) => ({ id: document.id, ...document.data() })); }

export async function createPromotionEntitlement(db: ReaderPlatformDb, input: { readerUid: string; tenantId: string; assetId: string; correlationId: string }): Promise<string> { await requireActiveVerifiedReader(db, input.readerUid); let entitlementId = ""; await db.runTransaction(async (transaction) => { entitlementId = await createEntitlementInTransaction(db, transaction, { ...input, source: "promotion" }); }); return entitlementId; }
