import { normalizeReaderEmail, requireNonEmpty, sha256Id } from "../reader-contracts/index.ts";
import { appendReaderAuditEvent } from "./audit-service.ts";
import { createEntitlementInTransaction } from "./entitlement-service.ts";
import { readerPlatformCollections, serverTimestamp, type ReaderPlatformDb } from "./service-support.ts";

export async function claimPendingPurchase(db: ReaderPlatformDb, input: { claimId: string; readerUid: string; verifiedEmail: string; emailVerified: boolean; correlationId: string }): Promise<{ purchaseId: string; entitlementIds: string[]; replay: boolean }> {
  if (!input.emailVerified) throw new Error("READER_EMAIL_NOT_VERIFIED"); const uid = requireNonEmpty(input.readerUid, "readerUid"); const claimRef = db.collection(readerPlatformCollections.claims).doc(requireNonEmpty(input.claimId, "claimId")); let result = { purchaseId: "", entitlementIds: [] as string[], replay: false }; let emailMismatch = false;
  await db.runTransaction(async (transaction) => { const claimSnapshot = await transaction.get(claimRef); if (!claimSnapshot.exists) throw new Error("PENDING_CLAIM_NOT_FOUND"); const claim = claimSnapshot.data() || {}; result.purchaseId = String(claim.purchaseId || ""); if (claim.status === "claimed") { if (claim.claimedUid !== uid) throw new Error("PURCHASE_ALREADY_CLAIMED"); result.entitlementIds = Array.isArray(claim.entitlementIds) ? claim.entitlementIds : []; result.replay = true; return; } if (claim.status !== "unclaimed") throw new Error("PURCHASE_CLAIM_BLOCKED");
    const suppliedEmailHash = sha256Id("reader-purchase-email", normalizeReaderEmail(input.verifiedEmail)); if (claim.purchaseEmailHash !== suppliedEmailHash) { emailMismatch = true; transaction.update(claimRef, { status: "blocked", manualReviewRequired: true, blockedReason: "verified_email_mismatch", updatedAt: serverTimestamp() }); await appendReaderAuditEvent(db, { eventType: "purchase_claim.blocked", actorType: "reader", actorId: uid, subjectType: "claim", subjectId: input.claimId, correlationId: input.correlationId, idempotencyKey: `email-mismatch:${uid}`, metadata: { reason: "verified_email_mismatch" } }, transaction); return; }
    const itemsQuery = db.collection(readerPlatformCollections.purchaseItems).where("purchaseId", "==", result.purchaseId).where("status", "==", "paid"); const items = await transaction.get(itemsQuery); if (items.empty) throw new Error("PURCHASE_HAS_NO_CLAIMABLE_ITEMS");
    const entitlementSnapshots = await Promise.all(items.docs.map((document) => { const item = document.data(); const id = sha256Id("reader-entitlement", uid, String(item.tenantId), String(item.assetId), document.id); return transaction.get(db.collection(readerPlatformCollections.entitlements).doc(id)); }));
    for (const [index, document] of items.docs.entries()) { const item = document.data(); result.entitlementIds.push(await createEntitlementInTransaction(db, transaction, { readerUid: uid, tenantId: String(item.tenantId), assetId: String(item.assetId), purchaseId: result.purchaseId, purchaseLineItemId: document.id, source: "purchase", correlationId: input.correlationId }, entitlementSnapshots[index])); }
    transaction.update(claimRef, { status: "claimed", claimedUid: uid, claimedAt: serverTimestamp(), entitlementIds: result.entitlementIds, manualReviewRequired: false, blockedReason: null, updatedAt: serverTimestamp() });
    await appendReaderAuditEvent(db, { eventType: "purchase_claim.claimed", actorType: "reader", actorId: uid, subjectType: "claim", subjectId: input.claimId, correlationId: input.correlationId, idempotencyKey: `claimed:${uid}`, metadata: { purchaseId: result.purchaseId, entitlementCount: result.entitlementIds.length } }, transaction);
  }); if (emailMismatch) throw new Error("PURCHASE_EMAIL_MISMATCH"); return result;
}
