import { normalizeReaderEmail, requireNonEmpty, sha256Id } from "../reader-contracts/index.ts";
import { appendReaderAuditEvent } from "./audit-service.ts";
import { deterministicPurchaseLineItemId, validatePurchaseLineItem, type CanonicalPurchaseLineInput } from "./purchase-line-item-service.ts";
import { readerPlatformCollections, serverTimestamp, type ReaderPlatformDb } from "./service-support.ts";
export interface RecordStripePurchaseInput { stripeAccountId?: string | null; stripeCheckoutSessionId: string; stripePaymentIntentId?: string | null; stripeCustomerId?: string | null; stripeEventId: string; stripeEventCreated: number; purchaseEmail: string; currency: string; amountTotalMinor: number; lineItems: CanonicalPurchaseLineInput[]; correlationId: string; }
export function deterministicPurchaseId(stripeAccountId: string | null | undefined, checkoutSessionId: string): string { return sha256Id("reader-purchase", stripeAccountId || "platform", requireNonEmpty(checkoutSessionId, "stripeCheckoutSessionId")); }
export async function recordPaidStripePurchase(db: ReaderPlatformDb, input: RecordStripePurchaseInput): Promise<{ purchaseId: string; claimId: string; replay: boolean }> {
  if (!input.lineItems.length) throw new Error("PURCHASE_LINE_ITEMS_REQUIRED"); input.lineItems.forEach(validatePurchaseLineItem); const purchaseEmailNormalized = normalizeReaderEmail(input.purchaseEmail); if (!purchaseEmailNormalized.includes("@")) throw new Error("PURCHASE_EMAIL_INVALID");
  const purchaseId = deterministicPurchaseId(input.stripeAccountId, input.stripeCheckoutSessionId); const claimId = sha256Id("pending-purchase-claim", purchaseId); const purchaseRef = db.collection(readerPlatformCollections.purchases).doc(purchaseId); const claimRef = db.collection(readerPlatformCollections.claims).doc(claimId); let replay = false;
  await db.runTransaction(async (transaction) => { const [existing, claimSnapshot] = await Promise.all([transaction.get(purchaseRef), transaction.get(claimRef)]); const existingData = existing.data() || {}; if (existing.exists && existingData.stripeEventId === input.stripeEventId) { replay = true; return; } if (existing.exists && Number(existingData.lastStripeEventCreated || 0) > input.stripeEventCreated) { replay = true; return; } const emailHash = sha256Id("reader-purchase-email", purchaseEmailNormalized);
    transaction.set(purchaseRef, { id: purchaseId, stripeAccountId: input.stripeAccountId?.trim() || "platform", stripeCheckoutSessionId: input.stripeCheckoutSessionId, stripePaymentIntentId: input.stripePaymentIntentId?.trim() || null, stripeCustomerId: input.stripeCustomerId?.trim() || null, stripeEventId: input.stripeEventId, purchaseEmailNormalized, purchaseEmailHash: emailHash, currency: input.currency.toLowerCase(), amountTotalMinor: input.amountTotalMinor, amountRefundedMinor: Number(existingData.amountRefundedMinor || 0), lineItemCount: input.lineItems.length, paymentStatus: "paid", disputeStatus: existingData.disputeStatus || "none", idempotencyKey: purchaseId, lastStripeEventCreated: input.stripeEventCreated, createdAt: existingData.createdAt || serverTimestamp(), updatedAt: serverTimestamp() }, { merge: true });
    for (const item of input.lineItems) { const itemId = deterministicPurchaseLineItemId(purchaseId, item); transaction.set(db.collection(readerPlatformCollections.purchaseItems).doc(itemId), { id: itemId, purchaseId, stripeLineItemId: item.stripeLineItemId, stripePriceId: item.stripePriceId?.trim() || null, stripeProductId: item.stripeProductId?.trim() || null, tenantId: item.tenantId, assetId: item.assetId, quantity: item.quantity, currency: item.currency.toLowerCase(), amountTotalMinor: item.amountTotalMinor, amountRefundedMinor: 0, status: "paid", createdAt: serverTimestamp(), updatedAt: serverTimestamp() }, { merge: true }); }
    if (!claimSnapshot.exists) transaction.create(claimRef, { id: claimId, purchaseId, purchaseEmailHash: emailHash, status: "unclaimed", claimedUid: null, claimedAt: null, entitlementIds: [], manualReviewRequired: false, blockedReason: null, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
    await appendReaderAuditEvent(db, { eventType: "purchase.paid", actorType: "stripe", actorId: input.stripeEventId, subjectType: "purchase", subjectId: purchaseId, correlationId: input.correlationId, idempotencyKey: input.stripeEventId, metadata: { lineItemCount: input.lineItems.length, amountTotalMinor: input.amountTotalMinor } }, transaction);
  }); return { purchaseId, claimId, replay };
}

export async function applyPurchaseItemFinancialTransition(db: ReaderPlatformDb, input: { purchaseId: string; purchaseLineItemId: string; transition: "full_refund" | "partial_refund" | "dispute_opened" | "dispute_won" | "dispute_lost"; amountRefundedMinor?: number; stripeEventId: string; correlationId: string }): Promise<void> {
  const purchaseRef = db.collection(readerPlatformCollections.purchases).doc(input.purchaseId); const itemRef = db.collection(readerPlatformCollections.purchaseItems).doc(input.purchaseLineItemId);
  await db.runTransaction(async (transaction) => { const entitlementQuery = db.collection(readerPlatformCollections.entitlements).where("purchaseLineItemId", "==", input.purchaseLineItemId); const [purchaseSnapshot, itemSnapshot, entitlements] = await Promise.all([transaction.get(purchaseRef), transaction.get(itemRef), transaction.get(entitlementQuery)]); if (!purchaseSnapshot.exists || !itemSnapshot.exists) throw new Error("PURCHASE_ITEM_NOT_FOUND"); const purchase = purchaseSnapshot.data() || {}; const item = itemSnapshot.data() || {}; if (item.purchaseId !== input.purchaseId) throw new Error("PURCHASE_ITEM_OWNERSHIP_INVALID");
    const itemStatus = input.transition === "full_refund" ? "refunded" : input.transition === "partial_refund" || input.transition === "dispute_lost" ? "revoked" : input.transition === "dispute_opened" ? "suspended" : "paid";
    const disputeStatus = input.transition === "dispute_opened" ? "open" : input.transition === "dispute_won" ? "won" : input.transition === "dispute_lost" ? "lost" : purchase.disputeStatus || "none";
    transaction.update(itemRef, { status: itemStatus, amountRefundedMinor: input.amountRefundedMinor ?? item.amountRefundedMinor ?? 0, updatedAt: serverTimestamp() }); transaction.update(purchaseRef, { paymentStatus: input.transition === "full_refund" ? "refunded" : input.transition === "partial_refund" ? "partially_refunded" : purchase.paymentStatus, disputeStatus, stripeEventId: input.stripeEventId, updatedAt: serverTimestamp() });
    const entitlementStatus = input.transition === "full_refund" ? "refunded" : input.transition === "dispute_opened" ? "suspended" : input.transition === "dispute_won" ? "active" : "revoked";
    for (const entitlement of entitlements.docs) { const current = entitlement.data().status; if ((current === "revoked" || current === "refunded") && entitlementStatus === "active") continue; transaction.update(entitlement.ref, { status: entitlementStatus, updatedAt: serverTimestamp(), ...(entitlementStatus === "refunded" ? { refundedAt: serverTimestamp() } : {}), ...(entitlementStatus === "revoked" ? { revokedAt: serverTimestamp() } : {}), ...(entitlementStatus === "suspended" ? { suspendedAt: serverTimestamp() } : {}), ...(entitlementStatus === "active" ? { suspendedAt: null } : {}) }); }
    await appendReaderAuditEvent(db, { eventType: `purchase_item.${input.transition}`, actorType: "stripe", actorId: input.stripeEventId, subjectType: "purchase_item", subjectId: input.purchaseLineItemId, correlationId: input.correlationId, idempotencyKey: input.stripeEventId, metadata: { entitlementCount: entitlements.size } }, transaction);
  });
}
