import { headers } from 'next/headers';
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { adminDb } from '@/lib/firebase-admin';

// Initialize Stripe matching the Checkout engine's Dahlia API
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
  apiVersion: '2026-06-24.dahlia', 
});

// This secret is generated by your Stripe Dashboard or Stripe CLI for local testing
const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET;

export async function POST(req: Request) {
  // Next.js App Router requires consuming the raw body as text for Stripe signature verification
  const body = await req.text();
  const headersList = headers();
  const signature = headersList.get('stripe-signature');

  let event: Stripe.Event;

  try {
    if (!signature || !endpointSecret) {
      throw new Error('Missing Stripe signature or Webhook Secret environment variable.');
    }
    // 1. Cryptographic Signature Verification
    event = stripe.webhooks.constructEvent(body, signature, endpointSecret);
  } catch (err: any) {
    console.error(`⚠️ Webhook Signature Verification Failed: ${err.message}`);
    return new NextResponse(`Webhook Error: ${err.message}`, { status: 400 });
  }

  // 2. Process the Successful Payment
  if (event.type === 'checkout.session.completed') {
    const session = event.data.object as Stripe.Checkout.Session;
    
    // Extract the exact metadata we injected during the checkout phase
    const assetId = session.metadata?.assetId;
    const tenantKey = session.metadata?.tenantKey;
    
    // Extract the buyer's contact info for Twilio passwordless login
    const customerEmail = session.customer_details?.email;
    const customerPhone = session.customer_details?.phone || ''; 

    if (assetId && tenantKey && customerEmail) {
      try {
        // 3. Provision the Vault Entitlement in Firestore
        // Using a composite ID prevents duplicate entitlements if webhooks fire twice
        const entitlementId = `${tenantKey}_${assetId}_${customerEmail}`;
        
        await adminDb.collection('entitlements').doc(entitlementId).set({
          assetId,
          tenantKey,
          customerEmail,
          customerPhone,
          status: 'active',
          amountTotal: session.amount_total,
          purchasedAt: new Date().toISOString(),
        });

        console.log(`✅ Vault Entitlement provisioned for: ${customerEmail} on asset: ${assetId}`);
      } catch (dbError) {
        console.error('🔥 Firestore Write Error during Webhook:', dbError);
        return new NextResponse('Database Error', { status: 500 });
      }
    } else {
      console.warn('⚠️ Webhook missing metadata or customer email. Cannot provision entitlement.');
    }
  }

  // 4. Return a 200 OK so Stripe knows we received it and doesn't retry
  return new NextResponse('Webhook processed successfully', { status: 200 });
}