allowBuilds:
  '@ampproject/toolbox-optimizer': true
  '@firebase/util': true
  '@google/genai': true
  '@sentry/cli': set this to true or false
  'es5-ext': true
  'protobufjs': true
  'sharp': true

overrides:
  jose: "4.15.5"
  jwks-rsa: "3.1.0"
